### ISSUE TITLE
Halocarbon naming

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#120]
Hector has HFC245fa, MAGICC has HFC245ca. However, emissions are the same for these gases.  Are they the same? or is something mislabeled?

**Comment by rplzzz** [comment]
GCAM processes the emissions passes them to the climate modules in `world.cpp`.  Here is the code for handling HFC245[cf]a:
```cpp
    if( hfc245faSummer.areEmissionsSet( period ) && hfc32Summer.areEmissionsSet( period ) && hfc365mfcSummer.areEmissionsSet( period ) && hfc152aSummer.areEmissionsSet( period ) ){
        // MAGICC needs HFC245fa in kton of HFC245ca
        mClimateModel->setEmissions( "HFC245ca", period,
                                     hfc245faSummer.getEmissions( period ) / HFC_CA_TO_FA +
                                     hfc32Summer.getEmissions( period ) * HFC32_TO_245 +
                                     hfc365mfcSummer.getEmissions( period ) * HFC365_TO_245 +
                                     hfc152aSummer.getEmissions( period ) * HFC152_TO_245);
        // For models that need ktonnes of HFC245fa (no single model should implement both of these):
        mClimateModel->setEmissions("HFC245fa", period,
                                    hfc245faSummer.getEmissions(period)+
                                    hfc32Summer.getEmissions( period ) * HFC32_TO_245 +
                                    hfc365mfcSummer.getEmissions( period ) * HFC365_TO_245 +
                                    hfc152aSummer.getEmissions( period ) * HFC152_TO_245);
    }
```
So, GCAM generates HFC245fa natively and converts to HFC245ca for models that require it.  The constants mentioned in the code above are:
```cpp
   const double HFC_CA_TO_FA = ( 950 / 640 );
   const double HFC32_TO_245 = ( 675.0 / 1030.0 );
   const double HFC152_TO_245 = ( 124.0 / 1030.0 );
   const double HFC365_TO_245 = ( 794.0 / 1030.0 );
```

Hmm.  Notice that HFC_CA_TO_FA is defined as `950 / 640` instead of `950.0 / 640.0`.  I'll bet this is a long-standing bug in GCAM that nobody has caught until now.  `950 / 640` will be evaluated using integer division, with a result of `int(1)`, instead of floating-point division with a result of `double(1.48)`.

The good news is, it's only the GCAM-MAGICC results that are wrong; GCAM-hector does not require conversion and is therefore correct.

**Comment by cahartin** [comment]
@rplzzz, this is awesome and will save me enormous amounts of time rather than trying to figure out what is going on. Cool.

**Comment by rplzzz** [comment]
No worries.  How much does HFC245 contribute to the total forcing?  I'm just wondering how much of a change to expect when I go to write this up for the GCAM core model committee.

**Comment by cahartin** [comment]
quick plot of HFC245fa under RCP45 from Hector.
![hfc245fa](https://cloud.githubusercontent.com/assets/7500729/11063838/351cd84e-8787-11e5-9ea8-19e33a25ba5d.png)
