### ISSUE TITLE
Log files include git status info

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#131]
if available.

**Comment by rplzzz** [comment]
This is sort of tricky to do because you can't be certain that users will be running from inside a git repository.  Users that download a release won't have a repository, and users that link to libhector.a from another code won't either (or they might have a repository for an entirely different code!)  One thing you could do is to have a file named something like `version.h`, and in there you could put something like:
```
const std::string versionid = "..."
``` 
Then you'd have the makefile run a script that replaces the "..." with the output of `git describe --dirty`.  The logger could then #include version.h, and you could print the contents of that string at the start of each log file.  The only trick would be to do it in a way that doesn't force a rebuild of the entire project every time you run make.  

The question you have to ask yourself is, is all this really worth the trouble?  For non-developer users changing out their version of hector will probably be a rare event, so the extra information isn't too useful.  For developers, maybe it's best just to keep your experimental runs organized by giving them unique names in the input file.  You're going to have to do something like that to keep the runs from overwriting one another anyhow.

**Comment by bpbond** [comment]
Yeah, agreed, seems like a lot of trouble for only marginal benefit. Closing this, but reopen if you disagree.
