### ISSUE TITLE
Unread data in emissions files

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#139]
In a [comment](https://github.com/JGCRI/hector/pull/116#issuecomment-155457636) in #116 @cahartin wrote

> anything that does not end in _emissions does not get read into Hector and should be deleted from the emissions files.

I think it's 'SOx', 'NH3', 'C6F14', 'HALON1202' which are un-used.

Happy to submit a pull request to remove these if they are really not necessary. I didn't find references to them in the source.

**Comment by cahartin** [comment]
@rgieseke these are indeed not needed in hector.  that would be great if you wanted to submit a PR. 

@rpl and @ben:  that could get merged into master, since it wouldn't change any values in inputs/outputs/results.

**Comment by rplzzz** [comment]
Every time you change the hector input files someone has to go manually fix the GCAM-hector inputs (which use a slightly different history).  Having unused columns in the inputs costs us nothing.  Conversely, just because changing the input format doesn't affect the stand-alone version of hector doesn't mean it doesn't affect other hector users.  Do not change the input format lightly, and *definitely* do not treat it as a trivial patch when you do.

**Comment by rplzzz** [comment]
On second thought, this may not be a problem because input files with the extra columns should still work in hector.  So, if other users didn't update their emissions files accordingly, they probably wouldn't see any problems.  I still don't see why it's worth spending time on, but I'm not as opposed to it as I was 44 minutes ago.

**Comment by rgieseke** [comment]
I'd think it's worth not to have anything that is not needed by Hector in the input files. From a new user's perspective it can be frustrating to change some variable which doesn't do anything. Also helpful for people who try to figure out which output variables their IAM need to produce to get Hector to run.

The changes are here: https://github.com/rgieseke/hector/tree/remove-unused-variables

To make sure nothing changed I played a bit with [Daff](https://github.com/paulfitz/daff) and did a run of Hector without and with the removals, comparing the output streams.

Should I create a pull request against master if you like to include this?

**Comment by bpbond** [comment]
Closing, as this is fixed by commit bf6499f. Thanks @rgieseke
