### ISSUE TITLE
Internal version number

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#236]
Is the internal version number in 

https://github.com/JGCRI/hector/blob/master/headers/h_util.hpp#L29

on purpose only having 2 digits or should it be updated with 2.0.1 as well?

I've been thinking about having a better way to see from Pyhector with which Hector version it has been compiled. For the Python part of Pyhector we use [Versioneer](https://github.com/warner/python-versioneer) which takes the version string from the git commit or tag.

It seems something similar exists for C++: https://github.com/smessmer/gitversion
(Not sure if it would work with Hector.)

**Comment by rplzzz** [comment]
That looks like an error, although given that the change from v2.0.0 to v2.0.1 involved no changes to the code or data (only the license), we could probably let it slide.

Regarding getting the version information from the git commit (i.e., using something like `git describe`), the problem is that there isn't any way to guarantee that a Hector user has a copy of the git repository, or even that they have git installed at all.  Therefore, the version number _has_ to be in some object that is copied with the tree.  

Back in the day, VCs like RCS and CVS allowed you to insert a placeholder that the system would replace with the version information on check-in, but git doesn't have a capability like that, probably because you can't predict the commit-id until you know the contents of all of the files in the tree.  You could probably come up with some kind of tricky solution here, but it's probably easiest to have a pre-release checklist that includes updating the version string as a step in the process.
