### ISSUE TITLE
Compile against pre-built boost libraries?

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#248]
Based on the Wiki installation documentation, and the Makefile source, it looks like the Hector build process also has to compile Boost libraries from source. Is it possible to compile Hector against a satisfactory version of Boost that already exists on the machine (e.g. one installed via a package manager, such as `apt` for Ubuntu or `brew` on MacOS)?

If not, perhaps this could be accomplished though a variable like `BOOSTLIB` (`BOOSTLIB=/path/to/boost_X.Y.Z make hector`)?

**Comment by ashiklom** [comment]
Haven't tried running yet, but I was at least able to get Hector to compile with the following change to the `Makefile`:

```make
# BOOSTLIB = $(BOOSTROOT)/stage/lib
BOOSTLIB = $(BOOSTROOT)/lib
```

...and then running the following (for a Homebrew version of Boost): `BOOSTROOT=/usr/local/Cellar/boost/1_67_0 make hector`). So, the `BOOSTLIB` is pointing to a location that is only valid if boost is installed from source.

**Comment by rplzzz** [comment]
I think we could make this change permanent.  I'm not entirely sure how we came by the practice of linking to boost out of its build directories instead of from an installed location, but it would be easy enough for users that still wanted to build this way to symlink `${BOOSTROOT}/stage/lib` to `${BOOSTROOT}/lib`.  The only problem might be for Windows users.  The only Windows user on the dev team is out on extended leave right now, so I'll have to scrounge around for someone who can test it on that platform for me.

**Comment by ashiklom** [comment]
Issued a PR to this effect in #251. We can wait to pull it if you want to wait and see if this works on Windows.

**Comment by rplzzz** [comment]
Pralit reminded me that Windows builds use the visual studio configuration files and are therefore unaffected by anything we do in the Makefile.

**Comment by ashiklom** [comment]
A note related to this, build system (#249), and the R interface (#246). Leaving it here for documentation.

When installing the Hector R package branch, `BOOSTROOT` _has_ to be set. Otherwise, the package will fail to install with the following misleading error:

```
RcppExports.cpp:4:10: fatal error: 'Rcpp.h' file not found
#include <Rcpp.h>
         ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘hector’
```

This is because, if `BOOSTROOT` is unset, the compilation commands have a dangling `-I` flag, which screws up all the include paths following it.
