### ISSUE TITLE
2.1 release

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#289]
As discusssed https://github.com/JGCRI/hector/issues/287#issuecomment-461783647 Hector prints 2.1 as its version but there is no tag or release for 2.1

Would be good to keep to have for keeping in sync with Pyhector.

What's your policy for the R interface, is it also following releases?

2.1 was changed in the source code here: https://github.com/JGCRI/hector/commit/74cbead3f60865996f5311cc52ab6ba3aa6fe6bc

**Comment by rplzzz** [comment]
We should tag the 2.1 release.  I'll do that shortly.  We should probably also evaluate what we've done since then to see if there's enough there for another minor or patch-level release.

Regarding the R interface, once we're satisfied that it's no longer in beta, we'll synchronize its version numbering with Hector itself.  We're pretty close to doing that, pending resolution of a few complaints about the API from the rest of the team.

**Comment by rgieseke** [comment]
Can you tag 2.2.0 as well? We've changed Pyhector's version scheme to match Hector's. 

`2.1.0.0` (with a 4th digit denoting consecutive Pyhector versions).

**Comment by rplzzz** [comment]
Will do.

**Comment by rplzzz** [comment]
Version 2.2.0 is tagged and released.

**Comment by rgieseke** [comment]
Thanks! We've released 2.2.0.0 of Pyhector now! (Required some adjusting to the new RCPP layout of Hector but now updates should be straight forward again.)

**Comment by rplzzz** [comment]
Great!  Sorry for the repository reorg, but now that we're synced up, everything should be stable going forward.

**Comment by rgieseke** [comment]
No problem! @swillner figured out the remaining problems quickly!
