### ISSUE TITLE
M_PI constant not available on some old (Windows?) compilers

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#335]
Hector compilation on some systems (e.g. R 3.3 on Windows?) may fail with an error like the following:

```
temperature_component.cpp: In member function 'virtual void Hector::TemperatureComponent::prepareToRun()':
temperature_component.cpp:229:40: error: 'M_PI' was not declared in this scope
     taudif = pow(cas,2) / pow(csw,2) * M_PI / keff;                      // interior ocean heat uptake time scale, yr
                                        ^
make: *** [temperature_component.o] Error 1
```

As far as I can tell, this is because math constants are not (or at least, have not always been a part) of the C/C++ standard. A solution seems to be to include a block like the following in our header files ([Stack Overflow source](https://stackoverflow.com/a/26065595/2477097)):

```cpp
#define _USE_MATH_DEFINES
#include <cmath>
```

I don't know if that solution has any unintended consequences, though. Since this doesn't seem to be an issue with more recent compiler toolchain versions, a simpler solution may be just to restrict Hector support to more recent versions of these toolchains.

**Comment by rplzzz** [comment]
We're already including `cmath` in `temperature_component.cpp`.  I guess the issue is that Microsoft guards all of the math macros in its version of `cmath` with `#ifdef _USE_MATH_DEFINES`, because of reasons.  

I don't love the idea of defining that macro and just leaving it.  In theory it should be harmless, but if that were universally true then Microsoft wouldn't have felt the need to guard those definitions in the first place.  One possibility is that we could create our own header (`hmath.hpp` or something like it) with contents:
```c++
#ifdef _MSC_VER
#define _USE_MATH_DEFINES
#endif
#include <cmath>
#ifdef _MSC_VER
#undef _USE_MATH_DEFINES
#endif
```
Then we just include that header anywhere we would otherwise include `cmath`.
