### ISSUE TITLE
CMIP6 ini files

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#339]
I know that @ashiklom has done some great work so that we can run Hector with non CO2 concentration driven runs, making it easy to set up a Hector core for certain CMIP6 concentration driven runs. But should we also consider adding CMIP6 ini files into the Hector repository? Sorry if this is a duplicative issue feature request but if someone is already working on it but I wanted to A) check to see if anyone else is already working on this and B) check to see if other thought this would be a worth while development.

**Comment by kdorheim** [comment]
From Alexey via the hector slack channel 

> I might suggest that we start with a separate repository for CMIP6 parameters, datasets, calibration scripts, etc., and then pull in the final data into the Hector repo. That will help keep the main Hector repository lean.
In the same spirit as hectortools and hectorcal, it may even make sense to make that it's own package -- e.g. hectordata ? A lot of other R packages do that, especially some of the spatial ones whose data are pretty large.

**Comment by kdorheim** [comment]
There is also the question of what CMIP emissions time series we want to use, those provided by RCMIP or directly from WCRP or something?

**Comment by ashiklom** [comment]
> There is also the question of what CMIP emissions time series we want to use, those provided by RCMIP or directly from WCRP or something?

My preference would be to stay as close to the source as possible, so WCRP would probably be better. To the extent that we do our own pre-processing, we should show/provide the scripts for doing that, both for transparency and (hopefully, unless everything changes) to make it easier to repeat this process for CMIP7 when it comes around.

**Comment by kdorheim** [comment]
ohh forward thinking!

**Comment by kdorheim** [comment]
> > There is also the question of what CMIP emissions time series we want to use, those provided by RCMIP or directly from WCRP or something?
> 
> My preference would be to stay as close to the source as possible, so WCRP would probably be better. To the extent that we do our own pre-processing, we should show/provide the scripts for doing that, both for transparency and (hopefully, unless everything changes) to make it easier to repeat this process for CMIP7 when it comes around.

ohh forward thinking!

**Comment by kdorheim** [comment]
Ah would there be any reason why GCAM would need the CMIP6 ini files?

**Comment by ssmithClimate** [comment]
There is no single source that would really be appropriate for hector. But I agree we should be as consistent as we can, but we shouldn't needlessly create more work for ourselves. For the concentrations, those came from the MAGICC group in the first place, so unless there's a known the data provided to RCMIP, those should be fine.  The climate models are provided gridded emission data -- those datasets are huge, and there's no need to process most of that since we have access to the original tabulated data that the gridded data files were created from. Note we've already processed the gridded historical open burning emissions data for use in GCAM - a code repo for that is on stash, so no need to re-do that part.

**Comment by ssmithClimate** [comment]
Regarding GCAM, as part of the CEDS->GCAM project we will be creating new hector input files that are consistent with CEDS, so that hector and GCAM's historical values are consistent with no discontinuities. I'm not aware of any need to calibrate GCAM to CMIP6 historical values (which are out of date already of course), but if someone did want to do that, then the CMIP6 history would be needed as well.

**Comment by kdorheim** [comment]
Instead of incorporating this into Hector we are developing a data package to keep the size of the Hector repo fairly small. See https://github.com/jgcri/hectordata for more information. Once `hectordata` is up and running there will need to be some documentation that links the two together,  see https://github.com/JGCRI/hectordata/issues/10.
