### ISSUE TITLE
OC RF in 2011

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#343]
While working on another project @ssmithClimate and I noticed that the OC RF seems unusually high in 2011. 

The Hector default RF for OC in 2011 is  -0.435 but we would expect this value to be some what comparable to the IPCC AR5 2011 OC central value of -0.23 with an uncertainty range of (-0.40, -0.08) but Hector's OC RF does not fall within this range. 

🤔 we are curious as to why this is happening are OC emissions being double counted? Is the OC RF code too high?

**Comment by ssmithClimate** [comment]
Looks like what is happening is that there’s a coefficient for forcing per unit emissions that's just multiplied against emissions. However, pre-industrial (e.g. 1850) emissions are not taken into account, since that is the baseline from which forcing is determined. That results in forcing that is too high, particularly for OC (since the pre-industrial emissions are BC-rich).

So the formula for BC and OC emissions should be changed to:
OC_forcing(t) = OC_forcing_per_unit_emission * ( OC_Emissions(t) - OC_Emissions(1850))

**Comment by kdorheim** [comment]
Is this issue occurring for multiple RF agents or just OC?

**Comment by ssmithClimate** [comment]
BC and OC (although the effect is much larger for OC).

**Comment by kdorheim** [comment]
How long would it take to you to implement a fix? Could you do it on a branch so that we can use that version for the HIRM runs we need to do to get the documentation paper wrapped up?

**Comment by ssmithClimate** [comment]
That sounds good. I suspect I can do that this afternoon.

**Comment by cahartin** [comment]
The forcing component makes all forcings relative to 1750.  There maybe a larger issue here that we want to make everything relative to 1850. In that case we could potentially update the forcing base year in the ini file to 1850.  What I would prefer not to happen is that ever gas is relative to a different year.

**Comment by ssmithClimate** [comment]
Changing to 1750 won't make much of a difference here, since historical open burning emissions are constant before 1850 (and don't change that much before mid-20th century). 

Forcing in terms of calibrating to numbers from IPCC or the literature should be relative to 1850, since that's the standard definition. Its fine if the forcing time series in hector are relative to 1750.

**Comment by cahartin** [comment]
gotcha. that makes sense. The emission files we read into Hector have BC/OC changing prior to 1850.

**Comment by ssmithClimate** [comment]
The anthropogenic portion of BC/OC will change prior to 1850 - which is largely biofuel use being proportional to population at that time. But the open burning part is assumed constant (although that probably is changing as well), and that's the dominant emission by then.

**Comment by kdorheim** [comment]
This seems to be a two fold issue 

1. Bug, why is Hector RF OC so high? 
2. Enchantment: make is so that the base RF is something that can be adjusted

**Comment by kdorheim** [comment]
@ssmithClimate started tackling this issue in https://github.com/JGCRI/hector/tree/bcoc_forcing as of today (September 2020) this branch does not completely resolve the issue but will be extremely helpful when we revisit this issue.

**Comment by kdorheim** [comment]
@ssmithClimate I think the problem with the OC and BC RF was addressed as part of the RF update we did earlier this year 

```
             scenario year variable      value units
1 Unnamed Hector core 2011    RF_BC  0.3749602  W/m2
2 Unnamed Hector core 2011    RF_OC -0.1060084  W/m2
```

![image](https://user-images.githubusercontent.com/27299759/205977257-5961ea1d-2fa8-4807-ae3d-2791c28c07fe.png)

okay to close?
