### ISSUE TITLE
Trailing whitespace in cpp source files

### ISSUE THREAD

**Issue by mnichol3** [JGCRI/hector#351]
The majority of the lines of cpp source code have trailing white space. When files are saved in RStudio, the trailing white space is removed per `hector.Rproj`:
```
StripTrailingWhitespace: Yes
```
Git detects these changes and presents them in pull requests along with meaningful changes. As many have noted, this is quickly becoming a nuisance in PRs as it adds tens of extra changed files.

**Comment by rplzzz** [comment]
Echoing my comment on #353, would it not be easier to change the `StripTrailingWhitespace` setting so that Rstudio does not make these changes?

**Comment by mnichol3** [comment]
That certainly is the simpler solution. However, the whitespace serves no purpose and has drawn numerous comments in PRs, so why not remove it from the existing code in addition to adding an IDE config file that removes any new trailing whitespace on save? 

In addition to making the code cleaner (clean code is good code), it'll make navigation via cursor/arrowkeys much easier in vim (I use vim a good bit for tweaking code in my Hector repo on `pic`) as well as more popular IDEs.

**Comment by rplzzz** [comment]
It serves no purpose, but it also causes no harm, and removing it does not make the code cleaner in any meaningful way because the spaces are invisible to humans.  

Meantime, the price you're paying is that you're demanding that people use an editor that conforms to that standard.  From the look of the diffs there is at least one editor in use that inserts indentation even on blank lines.  So, now we have to track down which one that is and reconfigure it or make the user change editors.  It seems like a lot of annoyance for not much benefit.

Finally, there is no way to ensure that new developers joining the team are using a compliant editor, so now we have to check the trailing whitespace on each PR, or we have to occasionally fix the trailing whitespace that will inevitably creep in.  It really is just a lot easier to have editors not automatically adjust whitespace.

BTW, trailing whitespace is significant in some dialects of Markdown.

**Comment by mnichol3** [comment]
> the price you're paying is that you're demanding that people use an editor that conforms to that standard

We already ask that people conform to the [Hector style guide](https://jgcri.github.io/hector/articles/manual/StyleGuide.html), which includes many common C++ standards & conventions. I fail to see how the addition of another [common convention](http://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace) is an issue.



> Finally, there is no way to ensure that new developers joining the team are using a compliant editor, so now we have to check the trailing whitespace on each PR, or we have to occasionally fix the trailing whitespace that will inevitably creep in

A good point, however it is pretty simple to have the dev remove trailing whitespace that may creep in and appear in their PR diffs.


> BTW, trailing whitespace is significant in some dialects of Markdown

True, but many interpreters allow more meaningful literals to accomplish the same thing. For example, Github Markdown treats two trailing spaces and `<br>` the same (creates a newline). The latter is easier for newer devs to comprehend IMO.

If the majority of current devs prefer to leave whitespace strewn throughout the code and instead change the `StripTrailingWhitespace` setting, I'll close this issue.

**Comment by bpbond** [comment]
Is this a recurring problem? I admit am curious about the editors in use and their behavior. We could also do a one-time `sed` processing step to remove trailing whitespace and see how quickly it comes back.

Anyway, on balance I'd vote with @rplzzz to not worry about this, though don't feel super strongly.
