### ISSUE TITLE
Question about GMST output by hector

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/hector#762]
I have noticed that the GMST (relative pre-industrial 1850-1900) values from GCAM7 (Hector) for 1980 to 2015 show similar trends to reanalysis data like ERA5, but the values are generally lower than those of the reanalysis data.
Can anyone explain why this is the case?
![Image](https://github.com/user-attachments/assets/bcd9046f-2dcc-4e3c-a1f5-a8c5bfb843d7)

**Comment by kdorheim** [comment]
Hi @jiangyongye, that is a great question, and there are several things that could be contributing to this discrepancy. It would be helpful if you could provide a bit more information about the NOAA, ERA5, HadCRUT5, and Berkely Earth data you are plotting in comparison. Are these time series also normalized to the 1850-1900 reference period? Was any additional processing done (smoothing, etc.), or are you only plotting the observation data for the GCAM periods?

**Comment by jiangyongye** [comment]
Hi @kdorheim ,
Thank you for responding to my question ：）

I apologize for not providing sufficient information earlier. I have downloaded the data from [the Climate Dashboard](https://climate.metoffice.cloud/temperature.html#datasets), and I believe these datasets are normalized to the 1850-1900 reference period as well.

I have double-checked the temperature variable used in these datasets, which is '2m air temperature'. I am wondering if this could be the cause of the discrepancy.（maybe Hector output 'ts', ERA5 and other models output 'tas' ? ）

Additionally, I have contacted Ouyang at PKU, who worked at PNNL, for his opinion. He suggested that Hector might just be 'colder' than other models, which is a characteristic of Hector. However, I am not certain if this is the case.

**Comment by kdorheim** [comment]
Hi @jiangyongy,  Ouyang is right. Hector does tend to run cool during the historical period, but I think your comment about the  '2m air temperature' is responsible for the difference in temperature you are seeing here. GMST is Hector's global mean surface temperature and will be cooler than the air temperature due to the heat capacity of the oceans, for Hector's '2m air temperature' you will want to query for `global-mean-air-temperature` which will return air temperature 2m above the surface relative to the 1850-1900 mean.

**Comment by jiangyongye** [comment]
Thanks @kdorheim  for detailed answer! That's all clear for me : )
