### ISSUE TITLE
Rename "core" to "coupler"?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#81]
to match GMD ms.

**Comment by rplzzz** [comment]
For what it's worth, I'm not too keen on renaming.  For one thing, the core provides more than just coupling between submodel (for example, logging is part of the core).  On top of that, I don't think it is particularly important to make the code internals consistent with the terminology used in the paper (which is not, after all, intended as a developer's guide).   Finally, renaming an important component like this is kind of a pain because it touches so many other components.  There is a lot of other stuff we could spend the time on instead.

Just my $.02 worth.

**Comment by bpbond** [comment]
That makes sense and is fine with me. Closing.
